// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.24.4
// source: clientCmd.proto

package game_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCmd int32

const (
	// 通用
	ClientCmd_ClientCmdUnspecified      ClientCmd = 0
	ClientCmd_ClientCmdLogin            ClientCmd = 1   //登录 消息体 ClientLogin
	ClientCmd_ClientCmdTableDestroy     ClientCmd = 2   //销毁用户当前牌桌 消息体 无
	ClientCmd_ClientCmdCurrentAppPage   ClientCmd = 201 //用户当前页面 ClientCurrentAppPage
	ClientCmd_ClientCmdFindMatchingGame ClientCmd = 202 //查询是否有匹配中的人满赛 消息体 无
	ClientCmd_ClientCmdQuitMatch        ClientCmd = 203 //退出当前比赛 消息体 ClientQuitMatch
	// 牌桌
	ClientCmd_ClientCmdJoin        ClientCmd = 2001 //加入 消息体 ClientJoin
	ClientCmd_ClientCmdJoining     ClientCmd = 2002 //加入进度 消息体 ClientJoining
	ClientCmd_ClientCmdEnter       ClientCmd = 2003 //牌桌加载完成 消息体 ClientEnter
	ClientCmd_ClientCmdLeave       ClientCmd = 2004 //离开 消息体 无
	ClientCmd_ClientCmdCheckInGame ClientCmd = 2005 //查询当前游戏牌桌 消息体 无
	ClientCmd_ClientCmdRejoin      ClientCmd = 2006 //重连进牌桌 消息体 ClientRejoin
	ClientCmd_ClientCmdChat        ClientCmd = 2007 //聊天 消息体 ClientChat
	ClientCmd_ClientCmdState       ClientCmd = 2008 //状态 消息体 ClientState
	ClientCmd_ClientCmdCreateTable ClientCmd = 2009 //创建房间 消息体 ClientCreateTable |返回ServerSelfJoin
	ClientCmd_ClientCmdVote        ClientCmd = 2010 //解散房间投票 消息体 ClientVote |返回ServerCmdVote
	ClientCmd_ClientCmdPrepare     ClientCmd = 2011 //准备 消息体 ClientPrepare |返回ServerCmdPrepare
	// 玩法
	ClientCmd_ClientCmdCallRate   ClientCmd = 4008 //叫分 消息体 ClientCallRate
	ClientCmd_ClientCmdCallDouble ClientCmd = 4009 //加倍 消息体 ClientCallDouble
	ClientCmd_ClientCmdPlay       ClientCmd = 4010 //出牌 消息体 ClientPlay
	ClientCmd_ClientCmdPass       ClientCmd = 4011 //过牌 消息体 无
	ClientCmd_ClientCmdFollow     ClientCmd = 4012 //跟牌 消息体 ClientFollow
)

// Enum value maps for ClientCmd.
var (
	ClientCmd_name = map[int32]string{
		0:    "ClientCmdUnspecified",
		1:    "ClientCmdLogin",
		2:    "ClientCmdTableDestroy",
		201:  "ClientCmdCurrentAppPage",
		202:  "ClientCmdFindMatchingGame",
		203:  "ClientCmdQuitMatch",
		2001: "ClientCmdJoin",
		2002: "ClientCmdJoining",
		2003: "ClientCmdEnter",
		2004: "ClientCmdLeave",
		2005: "ClientCmdCheckInGame",
		2006: "ClientCmdRejoin",
		2007: "ClientCmdChat",
		2008: "ClientCmdState",
		2009: "ClientCmdCreateTable",
		2010: "ClientCmdVote",
		2011: "ClientCmdPrepare",
		4008: "ClientCmdCallRate",
		4009: "ClientCmdCallDouble",
		4010: "ClientCmdPlay",
		4011: "ClientCmdPass",
		4012: "ClientCmdFollow",
	}
	ClientCmd_value = map[string]int32{
		"ClientCmdUnspecified":      0,
		"ClientCmdLogin":            1,
		"ClientCmdTableDestroy":     2,
		"ClientCmdCurrentAppPage":   201,
		"ClientCmdFindMatchingGame": 202,
		"ClientCmdQuitMatch":        203,
		"ClientCmdJoin":             2001,
		"ClientCmdJoining":          2002,
		"ClientCmdEnter":            2003,
		"ClientCmdLeave":            2004,
		"ClientCmdCheckInGame":      2005,
		"ClientCmdRejoin":           2006,
		"ClientCmdChat":             2007,
		"ClientCmdState":            2008,
		"ClientCmdCreateTable":      2009,
		"ClientCmdVote":             2010,
		"ClientCmdPrepare":          2011,
		"ClientCmdCallRate":         4008,
		"ClientCmdCallDouble":       4009,
		"ClientCmdPlay":             4010,
		"ClientCmdPass":             4011,
		"ClientCmdFollow":           4012,
	}
)

func (x ClientCmd) Enum() *ClientCmd {
	p := new(ClientCmd)
	*p = x
	return p
}

func (x ClientCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_clientCmd_proto_enumTypes[0].Descriptor()
}

func (ClientCmd) Type() protoreflect.EnumType {
	return &file_clientCmd_proto_enumTypes[0]
}

func (x ClientCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientCmd.Descriptor instead.
func (ClientCmd) EnumDescriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{0}
}

type ClientLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	DeviceNo string `protobuf:"bytes,2,opt,name=DeviceNo,proto3" json:"DeviceNo,omitempty"` //设备唯一码
}

func (x *ClientLogin) Reset() {
	*x = ClientLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLogin) ProtoMessage() {}

func (x *ClientLogin) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLogin.ProtoReflect.Descriptor instead.
func (*ClientLogin) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{0}
}

func (x *ClientLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientLogin) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

type ClientQuitMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *ClientQuitMatch) Reset() {
	*x = ClientQuitMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientQuitMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientQuitMatch) ProtoMessage() {}

func (x *ClientQuitMatch) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientQuitMatch.ProtoReflect.Descriptor instead.
func (*ClientQuitMatch) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{1}
}

func (x *ClientQuitMatch) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ClientJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	TableNo string `protobuf:"bytes,2,opt,name=TableNo,proto3" json:"TableNo,omitempty"` //私人牌桌桌号
}

func (x *ClientJoin) Reset() {
	*x = ClientJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoin) ProtoMessage() {}

func (x *ClientJoin) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoin.ProtoReflect.Descriptor instead.
func (*ClientJoin) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{2}
}

func (x *ClientJoin) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ClientJoin) GetTableNo() string {
	if x != nil {
		return x.TableNo
	}
	return ""
}

type ClientJoining struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=TableId,proto3" json:"TableId,omitempty"`  //ServerCmdSelfJoin返回
	Percent uint32 `protobuf:"varint,2,opt,name=Percent,proto3" json:"Percent,omitempty"` //加载进度
}

func (x *ClientJoining) Reset() {
	*x = ClientJoining{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJoining) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoining) ProtoMessage() {}

func (x *ClientJoining) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoining.ProtoReflect.Descriptor instead.
func (*ClientJoining) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{3}
}

func (x *ClientJoining) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ClientJoining) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type ClientEnter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=TableId,proto3" json:"TableId,omitempty"` //ServerCmdSelfJoin返回
}

func (x *ClientEnter) Reset() {
	*x = ClientEnter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnter) ProtoMessage() {}

func (x *ClientEnter) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnter.ProtoReflect.Descriptor instead.
func (*ClientEnter) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{4}
}

func (x *ClientEnter) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type ClientCallRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate uint32 `protobuf:"varint,1,opt,name=Rate,proto3" json:"Rate,omitempty"` //叫几分 对应值1、2、3 不叫为0
}

func (x *ClientCallRate) Reset() {
	*x = ClientCallRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCallRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCallRate) ProtoMessage() {}

func (x *ClientCallRate) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCallRate.ProtoReflect.Descriptor instead.
func (*ClientCallRate) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{5}
}

func (x *ClientCallRate) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ClientCallDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Double uint32 `protobuf:"varint,1,opt,name=Double,proto3" json:"Double,omitempty"` //加倍取值1 超级加倍取值2
}

func (x *ClientCallDouble) Reset() {
	*x = ClientCallDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCallDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCallDouble) ProtoMessage() {}

func (x *ClientCallDouble) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCallDouble.ProtoReflect.Descriptor instead.
func (*ClientCallDouble) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{6}
}

func (x *ClientCallDouble) GetDouble() uint32 {
	if x != nil {
		return x.Double
	}
	return 0
}

type ClientPlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []byte `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards,omitempty"`
}

func (x *ClientPlay) Reset() {
	*x = ClientPlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPlay) ProtoMessage() {}

func (x *ClientPlay) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPlay.ProtoReflect.Descriptor instead.
func (*ClientPlay) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{7}
}

func (x *ClientPlay) GetCards() []byte {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ClientFollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []byte `protobuf:"bytes,1,opt,name=Cards,proto3" json:"Cards,omitempty"`
}

func (x *ClientFollow) Reset() {
	*x = ClientFollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFollow) ProtoMessage() {}

func (x *ClientFollow) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFollow.ProtoReflect.Descriptor instead.
func (*ClientFollow) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{8}
}

func (x *ClientFollow) GetCards() []byte {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ClientRejoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId  string `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	TableId string `protobuf:"bytes,2,opt,name=TableId,proto3" json:"TableId,omitempty"`
}

func (x *ClientRejoin) Reset() {
	*x = ClientRejoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRejoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRejoin) ProtoMessage() {}

func (x *ClientRejoin) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRejoin.ProtoReflect.Descriptor instead.
func (*ClientRejoin) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{9}
}

func (x *ClientRejoin) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ClientRejoin) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type ClientChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     ChatType `protobuf:"varint,1,opt,name=Type,proto3,enum=ChatType" json:"Type,omitempty"`
	ID       uint32   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	ToSeat   uint32   `protobuf:"varint,3,opt,name=ToSeat,proto3" json:"ToSeat,omitempty"`
	Quantity uint32   `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
}

func (x *ClientChat) Reset() {
	*x = ClientChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChat) ProtoMessage() {}

func (x *ClientChat) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChat.ProtoReflect.Descriptor instead.
func (*ClientChat) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{10}
}

func (x *ClientChat) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_ChatTypeUnspecified
}

func (x *ClientChat) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ClientChat) GetToSeat() uint32 {
	if x != nil {
		return x.ToSeat
	}
	return 0
}

func (x *ClientChat) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ClientState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosted bool `protobuf:"varint,1,opt,name=Hosted,proto3" json:"Hosted,omitempty"` //是否托管
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{11}
}

func (x *ClientState) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

type ClientCreateTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType   GameType `protobuf:"varint,1,opt,name=GameType,proto3,enum=GameType" json:"GameType,omitempty"` //游戏类型
	WithBomb   bool     `protobuf:"varint,2,opt,name=WithBomb,proto3" json:"WithBomb,omitempty"`               //是否带炸弹
	WithDouble bool     `protobuf:"varint,3,opt,name=WithDouble,proto3" json:"WithDouble,omitempty"`           //是否带加倍
	Decks      uint32   `protobuf:"varint,4,opt,name=Decks,proto3" json:"Decks,omitempty"`                     //局数
}

func (x *ClientCreateTable) Reset() {
	*x = ClientCreateTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCreateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCreateTable) ProtoMessage() {}

func (x *ClientCreateTable) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCreateTable.ProtoReflect.Descriptor instead.
func (*ClientCreateTable) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{12}
}

func (x *ClientCreateTable) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeUnspecified
}

func (x *ClientCreateTable) GetWithBomb() bool {
	if x != nil {
		return x.WithBomb
	}
	return false
}

func (x *ClientCreateTable) GetWithDouble() bool {
	if x != nil {
		return x.WithDouble
	}
	return false
}

func (x *ClientCreateTable) GetDecks() uint32 {
	if x != nil {
		return x.Decks
	}
	return 0
}

type ClientVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accept bool `protobuf:"varint,1,opt,name=Accept,proto3" json:"Accept,omitempty"` //是否同意
}

func (x *ClientVote) Reset() {
	*x = ClientVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVote) ProtoMessage() {}

func (x *ClientVote) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVote.ProtoReflect.Descriptor instead.
func (*ClientVote) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{13}
}

func (x *ClientVote) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type ClientPrepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=Ready,proto3" json:"Ready,omitempty"` //是否准备
}

func (x *ClientPrepare) Reset() {
	*x = ClientPrepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPrepare) ProtoMessage() {}

func (x *ClientPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPrepare.ProtoReflect.Descriptor instead.
func (*ClientPrepare) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{14}
}

func (x *ClientPrepare) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ClientCurrentAppPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppPage AppPage `protobuf:"varint,1,opt,name=AppPage,proto3,enum=AppPage" json:"AppPage,omitempty"`
}

func (x *ClientCurrentAppPage) Reset() {
	*x = ClientCurrentAppPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCurrentAppPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCurrentAppPage) ProtoMessage() {}

func (x *ClientCurrentAppPage) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCurrentAppPage.ProtoReflect.Descriptor instead.
func (*ClientCurrentAppPage) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{15}
}

func (x *ClientCurrentAppPage) GetAppPage() AppPage {
	if x != nil {
		return x.AppPage
	}
	return AppPage_AppPageUnspecified
}

var File_clientCmd_proto protoreflect.FileDescriptor

var file_clientCmd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a,
	0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x22, 0x29,
	0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x69, 0x74, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x22, 0x43, 0x0a, 0x0d, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x27,
	0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x22, 0x2a, 0x0a,
	0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x24, 0x0a,
	0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x22, 0x40, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6a,
	0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6f, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x09, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x53, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x54, 0x6f, 0x53, 0x65, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x48, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x22, 0x8c, 0x01,
	0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x69,
	0x74, 0x68, 0x42, 0x6f, 0x6d, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x57, 0x69,
	0x74, 0x68, 0x42, 0x6f, 0x6d, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x57, 0x69, 0x74, 0x68,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65, 0x63, 0x6b, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x44, 0x65, 0x63, 0x6b, 0x73, 0x22, 0x24, 0x0a, 0x0a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x41, 0x70, 0x70, 0x50, 0x61, 0x67, 0x65, 0x52, 0x07, 0x41, 0x70,
	0x70, 0x50, 0x61, 0x67, 0x65, 0x2a, 0x90, 0x04, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6d, 0x64, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64,
	0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x17,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x41, 0x70, 0x70, 0x50, 0x61, 0x67, 0x65, 0x10, 0xc9, 0x01, 0x12, 0x1e, 0x0a, 0x19, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x10, 0xca, 0x01, 0x12, 0x17, 0x0a, 0x12, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x51, 0x75, 0x69, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x10, 0xcb, 0x01, 0x12, 0x12, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64,
	0x4a, 0x6f, 0x69, 0x6e, 0x10, 0xd1, 0x0f, 0x12, 0x15, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x6d, 0x64, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0xd2, 0x0f, 0x12, 0x13,
	0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x10, 0xd3, 0x0f, 0x12, 0x13, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x10, 0xd4, 0x0f, 0x12, 0x19, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x10, 0xd5, 0x0f, 0x12, 0x14, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64,
	0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x10, 0xd6, 0x0f, 0x12, 0x12, 0x0a, 0x0d, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43, 0x68, 0x61, 0x74, 0x10, 0xd7, 0x0f, 0x12, 0x13, 0x0a,
	0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10,
	0xd8, 0x0f, 0x12, 0x19, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x10, 0xd9, 0x0f, 0x12, 0x12, 0x0a,
	0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x10, 0xda,
	0x0f, 0x12, 0x15, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x10, 0xdb, 0x0f, 0x12, 0x16, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x10, 0xa8, 0x1f,
	0x12, 0x18, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x43, 0x61, 0x6c,
	0x6c, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x10, 0xa9, 0x1f, 0x12, 0x12, 0x0a, 0x0d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x10, 0xaa, 0x1f, 0x12, 0x12,
	0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x50, 0x61, 0x73, 0x73, 0x10,
	0xab, 0x1f, 0x12, 0x14, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0xac, 0x1f, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x3b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientCmd_proto_rawDescOnce sync.Once
	file_clientCmd_proto_rawDescData = file_clientCmd_proto_rawDesc
)

func file_clientCmd_proto_rawDescGZIP() []byte {
	file_clientCmd_proto_rawDescOnce.Do(func() {
		file_clientCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientCmd_proto_rawDescData)
	})
	return file_clientCmd_proto_rawDescData
}

var file_clientCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_clientCmd_proto_goTypes = []interface{}{
	(ClientCmd)(0),               // 0: ClientCmd
	(*ClientLogin)(nil),          // 1: ClientLogin
	(*ClientQuitMatch)(nil),      // 2: ClientQuitMatch
	(*ClientJoin)(nil),           // 3: ClientJoin
	(*ClientJoining)(nil),        // 4: ClientJoining
	(*ClientEnter)(nil),          // 5: ClientEnter
	(*ClientCallRate)(nil),       // 6: ClientCallRate
	(*ClientCallDouble)(nil),     // 7: ClientCallDouble
	(*ClientPlay)(nil),           // 8: ClientPlay
	(*ClientFollow)(nil),         // 9: ClientFollow
	(*ClientRejoin)(nil),         // 10: ClientRejoin
	(*ClientChat)(nil),           // 11: ClientChat
	(*ClientState)(nil),          // 12: ClientState
	(*ClientCreateTable)(nil),    // 13: ClientCreateTable
	(*ClientVote)(nil),           // 14: ClientVote
	(*ClientPrepare)(nil),        // 15: ClientPrepare
	(*ClientCurrentAppPage)(nil), // 16: ClientCurrentAppPage
	(ChatType)(0),                // 17: ChatType
	(GameType)(0),                // 18: GameType
	(AppPage)(0),                 // 19: AppPage
}
var file_clientCmd_proto_depIdxs = []int32{
	17, // 0: ClientChat.Type:type_name -> ChatType
	18, // 1: ClientCreateTable.GameType:type_name -> GameType
	19, // 2: ClientCurrentAppPage.AppPage:type_name -> AppPage
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_clientCmd_proto_init() }
func file_clientCmd_proto_init() {
	if File_clientCmd_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_clientCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientQuitMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJoining); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientEnter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCallRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCallDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientFollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRejoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCreateTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPrepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientCmd_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCurrentAppPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientCmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientCmd_proto_goTypes,
		DependencyIndexes: file_clientCmd_proto_depIdxs,
		EnumInfos:         file_clientCmd_proto_enumTypes,
		MessageInfos:      file_clientCmd_proto_msgTypes,
	}.Build()
	File_clientCmd_proto = out.File
	file_clientCmd_proto_rawDesc = nil
	file_clientCmd_proto_goTypes = nil
	file_clientCmd_proto_depIdxs = nil
}
