// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.24.4
// source: tableData.proto

package table_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	control "github.com/go-tron/server-proto/pb/control"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTopic int32

const (
	DataTopic_DataTopicUnspecified DataTopic = 0
	DataTopic_DataTopicTableEnd    DataTopic = 1
)

// Enum value maps for DataTopic.
var (
	DataTopic_name = map[int32]string{
		0: "DataTopicUnspecified",
		1: "DataTopicTableEnd",
	}
	DataTopic_value = map[string]int32{
		"DataTopicUnspecified": 0,
		"DataTopicTableEnd":    1,
	}
)

func (x DataTopic) Enum() *DataTopic {
	p := new(DataTopic)
	*p = x
	return p
}

func (x DataTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_tableData_proto_enumTypes[0].Descriptor()
}

func (DataTopic) Type() protoreflect.EnumType {
	return &file_tableData_proto_enumTypes[0]
}

func (x DataTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataTopic.Descriptor instead.
func (DataTopic) EnumDescriptor() ([]byte, []int) {
	return file_tableData_proto_rawDescGZIP(), []int{0}
}

type TableEndData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config    *control.TableConfig `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	CreatedAt string               `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	StartAt   string               `protobuf:"bytes,3,opt,name=StartAt,proto3" json:"StartAt,omitempty"`
	EndAt     string               `protobuf:"bytes,4,opt,name=EndAt,proto3" json:"EndAt,omitempty"`
	Users     []*UserData          `protobuf:"bytes,5,rep,name=Users,proto3" json:"Users,omitempty"`
	Decks     []*DeckData          `protobuf:"bytes,6,rep,name=Decks,proto3" json:"Decks,omitempty"`
}

func (x *TableEndData) Reset() {
	*x = TableEndData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableEndData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableEndData) ProtoMessage() {}

func (x *TableEndData) ProtoReflect() protoreflect.Message {
	mi := &file_tableData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableEndData.ProtoReflect.Descriptor instead.
func (*TableEndData) Descriptor() ([]byte, []int) {
	return file_tableData_proto_rawDescGZIP(), []int{0}
}

func (x *TableEndData) GetConfig() *control.TableConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TableEndData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TableEndData) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *TableEndData) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *TableEndData) GetUsers() []*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TableEndData) GetDecks() []*DeckData {
	if x != nil {
		return x.Decks
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot    bool   `protobuf:"varint,1,opt,name=Robot,proto3" json:"Robot,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserNo   string `protobuf:"bytes,3,opt,name=UserNo,proto3" json:"UserNo,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender   uint32 `protobuf:"varint,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Seat     uint32 `protobuf:"varint,7,opt,name=Seat,proto3" json:"Seat,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_tableData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_tableData_proto_rawDescGZIP(), []int{1}
}

func (x *UserData) GetRobot() bool {
	if x != nil {
		return x.Robot
	}
	return false
}

func (x *UserData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserData) GetUserNo() string {
	if x != nil {
		return x.UserNo
	}
	return ""
}

func (x *UserData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserData) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserData) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

type DeckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId  int64         `protobuf:"varint,1,opt,name=DeckId,proto3" json:"DeckId,omitempty"`
	DeckNo  uint32        `protobuf:"varint,2,opt,name=DeckNo,proto3" json:"DeckNo,omitempty"`
	StartAt string        `protobuf:"bytes,3,opt,name=StartAt,proto3" json:"StartAt,omitempty"`
	EndAt   string        `protobuf:"bytes,4,opt,name=EndAt,proto3" json:"EndAt,omitempty"`
	Records []*DeckRecord `protobuf:"bytes,5,rep,name=Records,proto3" json:"Records,omitempty"`
}

func (x *DeckData) Reset() {
	*x = DeckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tableData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckData) ProtoMessage() {}

func (x *DeckData) ProtoReflect() protoreflect.Message {
	mi := &file_tableData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckData.ProtoReflect.Descriptor instead.
func (*DeckData) Descriptor() ([]byte, []int) {
	return file_tableData_proto_rawDescGZIP(), []int{2}
}

func (x *DeckData) GetDeckId() int64 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *DeckData) GetDeckNo() uint32 {
	if x != nil {
		return x.DeckNo
	}
	return 0
}

func (x *DeckData) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *DeckData) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *DeckData) GetRecords() []*DeckRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_tableData_proto protoreflect.FileDescriptor

var file_tableData_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x62, 0x1a, 0x0b, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x5f, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70,
	0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x28, 0x0a, 0x05, 0x44, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x6b,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x44, 0x65, 0x63, 0x6b, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x65, 0x61, 0x74, 0x22, 0x9a,
	0x01, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x44, 0x65, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x63, 0x6b, 0x4e, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x44, 0x65, 0x63, 0x6b, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2a, 0x3c, 0x0a, 0x09, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x3b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tableData_proto_rawDescOnce sync.Once
	file_tableData_proto_rawDescData = file_tableData_proto_rawDesc
)

func file_tableData_proto_rawDescGZIP() []byte {
	file_tableData_proto_rawDescOnce.Do(func() {
		file_tableData_proto_rawDescData = protoimpl.X.CompressGZIP(file_tableData_proto_rawDescData)
	})
	return file_tableData_proto_rawDescData
}

var file_tableData_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tableData_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tableData_proto_goTypes = []interface{}{
	(DataTopic)(0),              // 0: table_pb.DataTopic
	(*TableEndData)(nil),        // 1: table_pb.TableEndData
	(*UserData)(nil),            // 2: table_pb.UserData
	(*DeckData)(nil),            // 3: table_pb.DeckData
	(*control.TableConfig)(nil), // 4: control_pb.TableConfig
	(*DeckRecord)(nil),          // 5: table_pb.DeckRecord
}
var file_tableData_proto_depIdxs = []int32{
	4, // 0: table_pb.TableEndData.Config:type_name -> control_pb.TableConfig
	2, // 1: table_pb.TableEndData.Users:type_name -> table_pb.UserData
	3, // 2: table_pb.TableEndData.Decks:type_name -> table_pb.DeckData
	5, // 3: table_pb.DeckData.Records:type_name -> table_pb.DeckRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tableData_proto_init() }
func file_tableData_proto_init() {
	if File_tableData_proto != nil {
		return
	}
	file_table_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tableData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableEndData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tableData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tableData_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tableData_proto_goTypes,
		DependencyIndexes: file_tableData_proto_depIdxs,
		EnumInfos:         file_tableData_proto_enumTypes,
		MessageInfos:      file_tableData_proto_msgTypes,
	}.Build()
	File_tableData_proto = out.File
	file_tableData_proto_rawDesc = nil
	file_tableData_proto_goTypes = nil
	file_tableData_proto_depIdxs = nil
}
