// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: tableCluster.proto

package table_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TableClusterSrv_NodeListSrv_FullMethodName   = "/table_pb.TableClusterSrv/NodeListSrv"
	TableClusterSrv_NodeOpenSrv_FullMethodName   = "/table_pb.TableClusterSrv/NodeOpenSrv"
	TableClusterSrv_NodeCloseSrv_FullMethodName  = "/table_pb.TableClusterSrv/NodeCloseSrv"
	TableClusterSrv_TableCountSrv_FullMethodName = "/table_pb.TableClusterSrv/TableCountSrv"
	TableClusterSrv_TableListSrv_FullMethodName  = "/table_pb.TableClusterSrv/TableListSrv"
	TableClusterSrv_TableGetSrv_FullMethodName   = "/table_pb.TableClusterSrv/TableGetSrv"
	TableClusterSrv_TableCloseSrv_FullMethodName = "/table_pb.TableClusterSrv/TableCloseSrv"
)

// TableClusterSrvClient is the client API for TableClusterSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableClusterSrvClient interface {
	NodeListSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeList, error)
	NodeOpenSrv(ctx context.Context, in *NodeNameReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NodeCloseSrv(ctx context.Context, in *NodeNameReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TableCountSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableCount, error)
	TableListSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableList, error)
	TableGetSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*Table, error)
	TableCloseSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tableClusterSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewTableClusterSrvClient(cc grpc.ClientConnInterface) TableClusterSrvClient {
	return &tableClusterSrvClient{cc}
}

func (c *tableClusterSrvClient) NodeListSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeList, error) {
	out := new(NodeList)
	err := c.cc.Invoke(ctx, TableClusterSrv_NodeListSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) NodeOpenSrv(ctx context.Context, in *NodeNameReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableClusterSrv_NodeOpenSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) NodeCloseSrv(ctx context.Context, in *NodeNameReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableClusterSrv_NodeCloseSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) TableCountSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableCount, error) {
	out := new(TableCount)
	err := c.cc.Invoke(ctx, TableClusterSrv_TableCountSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) TableListSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableList, error) {
	out := new(TableList)
	err := c.cc.Invoke(ctx, TableClusterSrv_TableListSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) TableGetSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := c.cc.Invoke(ctx, TableClusterSrv_TableGetSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClusterSrvClient) TableCloseSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableClusterSrv_TableCloseSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableClusterSrvServer is the server API for TableClusterSrv service.
// All implementations must embed UnimplementedTableClusterSrvServer
// for forward compatibility
type TableClusterSrvServer interface {
	NodeListSrv(context.Context, *emptypb.Empty) (*NodeList, error)
	NodeOpenSrv(context.Context, *NodeNameReq) (*emptypb.Empty, error)
	NodeCloseSrv(context.Context, *NodeNameReq) (*emptypb.Empty, error)
	TableCountSrv(context.Context, *TableQueryReq) (*TableCount, error)
	TableListSrv(context.Context, *TableQueryReq) (*TableList, error)
	TableGetSrv(context.Context, *TableIdReq) (*Table, error)
	TableCloseSrv(context.Context, *TableIdReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedTableClusterSrvServer()
}

// UnimplementedTableClusterSrvServer must be embedded to have forward compatible implementations.
type UnimplementedTableClusterSrvServer struct {
}

func (UnimplementedTableClusterSrvServer) NodeListSrv(context.Context, *emptypb.Empty) (*NodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeListSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) NodeOpenSrv(context.Context, *NodeNameReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeOpenSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) NodeCloseSrv(context.Context, *NodeNameReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeCloseSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) TableCountSrv(context.Context, *TableQueryReq) (*TableCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableCountSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) TableListSrv(context.Context, *TableQueryReq) (*TableList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableListSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) TableGetSrv(context.Context, *TableIdReq) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableGetSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) TableCloseSrv(context.Context, *TableIdReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableCloseSrv not implemented")
}
func (UnimplementedTableClusterSrvServer) mustEmbedUnimplementedTableClusterSrvServer() {}

// UnsafeTableClusterSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableClusterSrvServer will
// result in compilation errors.
type UnsafeTableClusterSrvServer interface {
	mustEmbedUnimplementedTableClusterSrvServer()
}

func RegisterTableClusterSrvServer(s grpc.ServiceRegistrar, srv TableClusterSrvServer) {
	s.RegisterService(&TableClusterSrv_ServiceDesc, srv)
}

func _TableClusterSrv_NodeListSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).NodeListSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_NodeListSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).NodeListSrv(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_NodeOpenSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).NodeOpenSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_NodeOpenSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).NodeOpenSrv(ctx, req.(*NodeNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_NodeCloseSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).NodeCloseSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_NodeCloseSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).NodeCloseSrv(ctx, req.(*NodeNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_TableCountSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).TableCountSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_TableCountSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).TableCountSrv(ctx, req.(*TableQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_TableListSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).TableListSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_TableListSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).TableListSrv(ctx, req.(*TableQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_TableGetSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).TableGetSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_TableGetSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).TableGetSrv(ctx, req.(*TableIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableClusterSrv_TableCloseSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableClusterSrvServer).TableCloseSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableClusterSrv_TableCloseSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableClusterSrvServer).TableCloseSrv(ctx, req.(*TableIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TableClusterSrv_ServiceDesc is the grpc.ServiceDesc for TableClusterSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableClusterSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "table_pb.TableClusterSrv",
	HandlerType: (*TableClusterSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeListSrv",
			Handler:    _TableClusterSrv_NodeListSrv_Handler,
		},
		{
			MethodName: "NodeOpenSrv",
			Handler:    _TableClusterSrv_NodeOpenSrv_Handler,
		},
		{
			MethodName: "NodeCloseSrv",
			Handler:    _TableClusterSrv_NodeCloseSrv_Handler,
		},
		{
			MethodName: "TableCountSrv",
			Handler:    _TableClusterSrv_TableCountSrv_Handler,
		},
		{
			MethodName: "TableListSrv",
			Handler:    _TableClusterSrv_TableListSrv_Handler,
		},
		{
			MethodName: "TableGetSrv",
			Handler:    _TableClusterSrv_TableGetSrv_Handler,
		},
		{
			MethodName: "TableCloseSrv",
			Handler:    _TableClusterSrv_TableCloseSrv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tableCluster.proto",
}
