// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: table.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Table_TableCountSrv_FullMethodName = "/game.data.Table/TableCountSrv"
	Table_TableListSrv_FullMethodName  = "/game.data.Table/TableListSrv"
	Table_TableGetSrv_FullMethodName   = "/game.data.Table/TableGetSrv"
)

// TableClient is the client API for Table service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableClient interface {
	TableCountSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TableCount, error)
	TableListSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TableList, error)
	TableGetSrv(ctx context.Context, in *TableGetReq, opts ...grpc.CallOption) (*TableVO, error)
}

type tableClient struct {
	cc grpc.ClientConnInterface
}

func NewTableClient(cc grpc.ClientConnInterface) TableClient {
	return &tableClient{cc}
}

func (c *tableClient) TableCountSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TableCount, error) {
	out := new(TableCount)
	err := c.cc.Invoke(ctx, Table_TableCountSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClient) TableListSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TableList, error) {
	out := new(TableList)
	err := c.cc.Invoke(ctx, Table_TableListSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableClient) TableGetSrv(ctx context.Context, in *TableGetReq, opts ...grpc.CallOption) (*TableVO, error) {
	out := new(TableVO)
	err := c.cc.Invoke(ctx, Table_TableGetSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableServer is the server API for Table service.
// All implementations must embed UnimplementedTableServer
// for forward compatibility
type TableServer interface {
	TableCountSrv(context.Context, *emptypb.Empty) (*TableCount, error)
	TableListSrv(context.Context, *emptypb.Empty) (*TableList, error)
	TableGetSrv(context.Context, *TableGetReq) (*TableVO, error)
	mustEmbedUnimplementedTableServer()
}

// UnimplementedTableServer must be embedded to have forward compatible implementations.
type UnimplementedTableServer struct {
}

func (UnimplementedTableServer) TableCountSrv(context.Context, *emptypb.Empty) (*TableCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableCountSrv not implemented")
}
func (UnimplementedTableServer) TableListSrv(context.Context, *emptypb.Empty) (*TableList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableListSrv not implemented")
}
func (UnimplementedTableServer) TableGetSrv(context.Context, *TableGetReq) (*TableVO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableGetSrv not implemented")
}
func (UnimplementedTableServer) mustEmbedUnimplementedTableServer() {}

// UnsafeTableServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableServer will
// result in compilation errors.
type UnsafeTableServer interface {
	mustEmbedUnimplementedTableServer()
}

func RegisterTableServer(s grpc.ServiceRegistrar, srv TableServer) {
	s.RegisterService(&Table_ServiceDesc, srv)
}

func _Table_TableCountSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServer).TableCountSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Table_TableCountSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServer).TableCountSrv(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Table_TableListSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServer).TableListSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Table_TableListSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServer).TableListSrv(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Table_TableGetSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServer).TableGetSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Table_TableGetSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServer).TableGetSrv(ctx, req.(*TableGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Table_ServiceDesc is the grpc.ServiceDesc for Table service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Table_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.data.Table",
	HandlerType: (*TableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TableCountSrv",
			Handler:    _Table_TableCountSrv_Handler,
		},
		{
			MethodName: "TableListSrv",
			Handler:    _Table_TableListSrv_Handler,
		},
		{
			MethodName: "TableGetSrv",
			Handler:    _Table_TableGetSrv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "table.proto",
}
