// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: userState.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户状态
type UserAction int32

const (
	UserAction_UserActionUnspecified    UserAction = 0
	UserAction_UserActionUserEnterGame  UserAction = 1 //进入游戏
	UserAction_UserActionUserLeaveGame  UserAction = 2 //离开游戏
	UserAction_UserActionUserEnterTable UserAction = 3 //进入牌桌
	UserAction_UserActionUserLeaveTable UserAction = 4 //离开牌桌
)

// Enum value maps for UserAction.
var (
	UserAction_name = map[int32]string{
		0: "UserActionUnspecified",
		1: "UserActionUserEnterGame",
		2: "UserActionUserLeaveGame",
		3: "UserActionUserEnterTable",
		4: "UserActionUserLeaveTable",
	}
	UserAction_value = map[string]int32{
		"UserActionUnspecified":    0,
		"UserActionUserEnterGame":  1,
		"UserActionUserLeaveGame":  2,
		"UserActionUserEnterTable": 3,
		"UserActionUserLeaveTable": 4,
	}
)

func (x UserAction) Enum() *UserAction {
	p := new(UserAction)
	*p = x
	return p
}

func (x UserAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAction) Descriptor() protoreflect.EnumDescriptor {
	return file_userState_proto_enumTypes[0].Descriptor()
}

func (UserAction) Type() protoreflect.EnumType {
	return &file_userState_proto_enumTypes[0]
}

func (x UserAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAction.Descriptor instead.
func (UserAction) EnumDescriptor() ([]byte, []int) {
	return file_userState_proto_rawDescGZIP(), []int{0}
}

type UserState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64        `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserAction   UserAction   `protobuf:"varint,2,opt,name=UserAction,proto3,enum=UserAction" json:"UserAction,omitempty"`
	GameId       string       `protobuf:"bytes,3,opt,name=GameId,proto3" json:"GameId,omitempty"`
	GameType     GameType     `protobuf:"varint,4,opt,name=GameType,proto3,enum=GameType" json:"GameType,omitempty"`             //游戏类型
	GameCategory GameCategory `protobuf:"varint,5,opt,name=GameCategory,proto3,enum=GameCategory" json:"GameCategory,omitempty"` //游戏类别
	GameConfigId uint32       `protobuf:"varint,6,opt,name=GameConfigId,proto3" json:"GameConfigId,omitempty"`
	TableId      string       `protobuf:"bytes,7,opt,name=TableId,proto3" json:"TableId,omitempty"`
}

func (x *UserState) Reset() {
	*x = UserState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userState_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserState) ProtoMessage() {}

func (x *UserState) ProtoReflect() protoreflect.Message {
	mi := &file_userState_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserState.ProtoReflect.Descriptor instead.
func (*UserState) Descriptor() ([]byte, []int) {
	return file_userState_proto_rawDescGZIP(), []int{0}
}

func (x *UserState) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserState) GetUserAction() UserAction {
	if x != nil {
		return x.UserAction
	}
	return UserAction_UserActionUnspecified
}

func (x *UserState) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserState) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeUnspecified
}

func (x *UserState) GetGameCategory() GameCategory {
	if x != nil {
		return x.GameCategory
	}
	return GameCategory_GameCategoryUnspecified
}

func (x *UserState) GetGameConfigId() uint32 {
	if x != nil {
		return x.GameConfigId
	}
	return 0
}

func (x *UserState) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

var File_userState_proto protoreflect.FileDescriptor

var file_userState_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02,
	0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x31, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x2a, 0x9d, 0x01, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x04,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_userState_proto_rawDescOnce sync.Once
	file_userState_proto_rawDescData = file_userState_proto_rawDesc
)

func file_userState_proto_rawDescGZIP() []byte {
	file_userState_proto_rawDescOnce.Do(func() {
		file_userState_proto_rawDescData = protoimpl.X.CompressGZIP(file_userState_proto_rawDescData)
	})
	return file_userState_proto_rawDescData
}

var file_userState_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userState_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_userState_proto_goTypes = []interface{}{
	(UserAction)(0),   // 0: UserAction
	(*UserState)(nil), // 1: UserState
	(GameType)(0),     // 2: GameType
	(GameCategory)(0), // 3: GameCategory
}
var file_userState_proto_depIdxs = []int32{
	0, // 0: UserState.UserAction:type_name -> UserAction
	2, // 1: UserState.GameType:type_name -> GameType
	3, // 2: UserState.GameCategory:type_name -> GameCategory
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userState_proto_init() }
func file_userState_proto_init() {
	if File_userState_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_userState_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userState_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userState_proto_goTypes,
		DependencyIndexes: file_userState_proto_depIdxs,
		EnumInfos:         file_userState_proto_enumTypes,
		MessageInfos:      file_userState_proto_msgTypes,
	}.Build()
	File_userState_proto = out.File
	file_userState_proto_rawDesc = nil
	file_userState_proto_goTypes = nil
	file_userState_proto_depIdxs = nil
}
