// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: tableMonitor.proto

package tableMonitor_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TableMonitor_NodeOpenSrv_FullMethodName   = "/tableMonitor_pb.TableMonitor/NodeOpenSrv"
	TableMonitor_NodeCloseSrv_FullMethodName  = "/tableMonitor_pb.TableMonitor/NodeCloseSrv"
	TableMonitor_TableFindSrv_FullMethodName  = "/tableMonitor_pb.TableMonitor/TableFindSrv"
	TableMonitor_TableCountSrv_FullMethodName = "/tableMonitor_pb.TableMonitor/TableCountSrv"
	TableMonitor_TableListSrv_FullMethodName  = "/tableMonitor_pb.TableMonitor/TableListSrv"
	TableMonitor_TableGetSrv_FullMethodName   = "/tableMonitor_pb.TableMonitor/TableGetSrv"
	TableMonitor_TableCloseSrv_FullMethodName = "/tableMonitor_pb.TableMonitor/TableCloseSrv"
)

// TableMonitorClient is the client API for TableMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableMonitorClient interface {
	NodeOpenSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NodeCloseSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TableFindSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*TableCount, error)
	TableCountSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableCount, error)
	TableListSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableList, error)
	TableGetSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*TableGetVO, error)
	TableCloseSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tableMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewTableMonitorClient(cc grpc.ClientConnInterface) TableMonitorClient {
	return &tableMonitorClient{cc}
}

func (c *tableMonitorClient) NodeOpenSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableMonitor_NodeOpenSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) NodeCloseSrv(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableMonitor_NodeCloseSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) TableFindSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*TableCount, error) {
	out := new(TableCount)
	err := c.cc.Invoke(ctx, TableMonitor_TableFindSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) TableCountSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableCount, error) {
	out := new(TableCount)
	err := c.cc.Invoke(ctx, TableMonitor_TableCountSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) TableListSrv(ctx context.Context, in *TableQueryReq, opts ...grpc.CallOption) (*TableList, error) {
	out := new(TableList)
	err := c.cc.Invoke(ctx, TableMonitor_TableListSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) TableGetSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*TableGetVO, error) {
	out := new(TableGetVO)
	err := c.cc.Invoke(ctx, TableMonitor_TableGetSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableMonitorClient) TableCloseSrv(ctx context.Context, in *TableIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableMonitor_TableCloseSrv_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableMonitorServer is the server API for TableMonitor service.
// All implementations must embed UnimplementedTableMonitorServer
// for forward compatibility
type TableMonitorServer interface {
	NodeOpenSrv(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	NodeCloseSrv(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	TableFindSrv(context.Context, *TableIdReq) (*TableCount, error)
	TableCountSrv(context.Context, *TableQueryReq) (*TableCount, error)
	TableListSrv(context.Context, *TableQueryReq) (*TableList, error)
	TableGetSrv(context.Context, *TableIdReq) (*TableGetVO, error)
	TableCloseSrv(context.Context, *TableIdReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedTableMonitorServer()
}

// UnimplementedTableMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedTableMonitorServer struct {
}

func (UnimplementedTableMonitorServer) NodeOpenSrv(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeOpenSrv not implemented")
}
func (UnimplementedTableMonitorServer) NodeCloseSrv(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeCloseSrv not implemented")
}
func (UnimplementedTableMonitorServer) TableFindSrv(context.Context, *TableIdReq) (*TableCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableFindSrv not implemented")
}
func (UnimplementedTableMonitorServer) TableCountSrv(context.Context, *TableQueryReq) (*TableCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableCountSrv not implemented")
}
func (UnimplementedTableMonitorServer) TableListSrv(context.Context, *TableQueryReq) (*TableList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableListSrv not implemented")
}
func (UnimplementedTableMonitorServer) TableGetSrv(context.Context, *TableIdReq) (*TableGetVO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableGetSrv not implemented")
}
func (UnimplementedTableMonitorServer) TableCloseSrv(context.Context, *TableIdReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TableCloseSrv not implemented")
}
func (UnimplementedTableMonitorServer) mustEmbedUnimplementedTableMonitorServer() {}

// UnsafeTableMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableMonitorServer will
// result in compilation errors.
type UnsafeTableMonitorServer interface {
	mustEmbedUnimplementedTableMonitorServer()
}

func RegisterTableMonitorServer(s grpc.ServiceRegistrar, srv TableMonitorServer) {
	s.RegisterService(&TableMonitor_ServiceDesc, srv)
}

func _TableMonitor_NodeOpenSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).NodeOpenSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_NodeOpenSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).NodeOpenSrv(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_NodeCloseSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).NodeCloseSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_NodeCloseSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).NodeCloseSrv(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_TableFindSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).TableFindSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_TableFindSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).TableFindSrv(ctx, req.(*TableIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_TableCountSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).TableCountSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_TableCountSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).TableCountSrv(ctx, req.(*TableQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_TableListSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).TableListSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_TableListSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).TableListSrv(ctx, req.(*TableQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_TableGetSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).TableGetSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_TableGetSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).TableGetSrv(ctx, req.(*TableIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableMonitor_TableCloseSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableMonitorServer).TableCloseSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableMonitor_TableCloseSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableMonitorServer).TableCloseSrv(ctx, req.(*TableIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TableMonitor_ServiceDesc is the grpc.ServiceDesc for TableMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tableMonitor_pb.TableMonitor",
	HandlerType: (*TableMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeOpenSrv",
			Handler:    _TableMonitor_NodeOpenSrv_Handler,
		},
		{
			MethodName: "NodeCloseSrv",
			Handler:    _TableMonitor_NodeCloseSrv_Handler,
		},
		{
			MethodName: "TableFindSrv",
			Handler:    _TableMonitor_TableFindSrv_Handler,
		},
		{
			MethodName: "TableCountSrv",
			Handler:    _TableMonitor_TableCountSrv_Handler,
		},
		{
			MethodName: "TableListSrv",
			Handler:    _TableMonitor_TableListSrv_Handler,
		},
		{
			MethodName: "TableGetSrv",
			Handler:    _TableMonitor_TableGetSrv_Handler,
		},
		{
			MethodName: "TableCloseSrv",
			Handler:    _TableMonitor_TableCloseSrv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tableMonitor.proto",
}
